a + 0 = a
a * 0 = 0
a + b = b + a
(a + b) + c = a + (b + c)
(a * b) + (c * b) = (a + c) * b
a + (S b) = S (a + b)
a * (S b) = a + (a * b)
a * b = b * a
(a * b) * c = a * (b * c)
(a * b) + (a * c) = (b + c) * a
(S m) + n = m + (S n)
x + (y + z) = y + (x + z)
