pdf : latex2
	pdflatex article

bibtex : latex
	bibtex article

latex :
	latex article

latex2 : bibtex
	latex article

clean :
	rm article.aux
	rm article.blg
	rm article.log
	rm article.pdf
	rm article.bbl
	rm article.dvi
	rm article.out
