pdf :
	latex article
	bibtex article
	latex article
	pdflatex article

.PHONY : clean
clean :
	rm -f article.aux
	rm -f article.blg
	rm -f article.log
	rm -f article.pdf
	rm -f article.bbl
	rm -f article.dvi
	rm -f article.out
